### ISSUE TITLE
What's this error?Can help me out?

### ISSUE THREAD

**Issue by sarancodes** [deepseagirl/degoogle#4]
usage: degoogle.py [-h] [-o OFFSET] [-p PAGES] [-t TIME_WINDOW] [-j] query
degoogle.py: error: the following arguments are required: query

->When i run the code this error pops up!

**Comment by deepseagirl** [comment]
you need to enter the text you wanna search for  

`python3 degoogle.py "search query here"`

**Comment by sarancodes** [comment]
Got it resolved.Thanks
